apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedag-graph
  namespace: default
data:
  graph.json: |
    {"graph": {"tutorial": {"tasks": {"print_date": {"downstream": ["sleep", "t4"], "upstream": []}, "sleep": {"downstream": ["templated"], "upstream": ["print_date"]}, "templated": {"downstream": [], "upstream": ["sleep"]}, "t4": {"downstream": [], "upstream": ["print_date"]}}, "roots": ["print_date"]}}}
