apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cfg-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-cfg
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sa-runner
    namespace: default
roleRef:
  kind: Role
  name: cfg-reader
  apiGroup: rbac.authorization.k8s.io
